import { CounterfactualExposurePlanner } from "./planner.js"; import type { ExposureGraph, Scenario } from "./types.js";
type Req={jsonrpc?:string;id?:unknown;method?:string;params?:any}; const schema=(required:string[],properties:Record<string,unknown>)=>({type:"object",required,properties,additionalProperties:false});
const tools=[
{name:"exposure_baseline",description:"Measure a sealed exposure graph without mutating it",inputSchema:schema(["graph"],{graph:{type:"object"}})},
{name:"exposure_simulate",description:"Simulate one intervention scenario against current exposure state",inputSchema:schema(["graph","scenario"],{graph:{type:"object"},scenario:{type:"object"}})},
{name:"exposure_rank",description:"Rank multiple counterfactual scenarios deterministically and identify Pareto-efficient options",inputSchema:schema(["graph","scenarios"],{graph:{type:"object"},scenarios:{type:"array"}})}];
export function handleMcp(req:Req):any{const id=req.id??null;if(req.method==="initialize")return{jsonrpc:"2.0",id,result:{protocolVersion:"2025-06-18",capabilities:{tools:{}},serverInfo:{name:"shpbl-counterfactual-exposure-planner",version:"1.0.0"}}};if(req.method==="notifications/initialized")return null;if(req.method==="tools/list")return{jsonrpc:"2.0",id,result:{tools}};if(req.method!=="tools/call")return{jsonrpc:"2.0",id,error:{code:-32601,message:"Method not found"}};try{const name=req.params?.name,args=req.params?.arguments??{};if(!["exposure_baseline","exposure_simulate","exposure_rank"].includes(name))return{jsonrpc:"2.0",id,error:{code:-32602,message:`E_TOOL: unknown tool ${String(name)}`}};const p=new CounterfactualExposurePlanner(args.graph as ExposureGraph);let value:unknown;if(name==="exposure_baseline")value=p.baseline();else if(name==="exposure_simulate")value=p.simulate(args.scenario as Scenario);else value=p.rank(args.scenarios as Scenario[]);return{jsonrpc:"2.0",id,result:{content:[{type:"text",text:JSON.stringify(value)}],structuredContent:value}};}catch(e){return{jsonrpc:"2.0",id,error:{code:-32000,message:e instanceof Error?e.message:String(e)}};}}
export function startStdio():void{let buffer="";process.stdin.setEncoding("utf8");process.stdin.on("data",chunk=>{buffer+=chunk;for(;;){const i=buffer.indexOf("\n");if(i<0)break;const line=buffer.slice(0,i).trim();buffer=buffer.slice(i+1);if(!line)continue;let req:Req;try{req=JSON.parse(line);}catch{process.stdout.write(JSON.stringify({jsonrpc:"2.0",id:null,error:{code:-32700,message:"Parse error"}})+"\n");continue;}const response=handleMcp(req);if(response!==null)process.stdout.write(JSON.stringify(response)+"\n");}});}

if(process.argv[1]&&process.argv[1].endsWith("mcp-server.js"))startStdio();
